# src/application/config/simulation/default_simulation.yaml
# Simulation configuration

# 文件配置
file_configs:
  machines:
    dir: "src/application/config/machines"
    selection:
      mode: "exclude"  # Options: "all", "include", "exclude"
      files:  # List of filenames to include or exclude based on mode
        - "default_machine.yaml"
        - "risky.yaml"
        # Add more machine files as needed
  players:
    dir: "src/application/config/players"
    selection:
      mode: "include"  # Options: "all", "include", "exclude"
      files:
        - "v1_player_cluster0.yaml"
        - "v1_player_cluster1.yaml"
        - "v1_player_cluster2.yaml"
        # Add more player files as needed

# Simulation parameters
max_spins: 15000          # 每个会话最大旋转次数
max_sim_duration: 300     # 模拟器运行最大时长(秒)
max_player_duration: 86400 # 玩家逻辑时间最大值(秒)
initial_balance: 5000.0
sessions_per_pair: 1000000   # 当前测试值，大规模时调整为更大值

# 并发控制参数（正确使用现有的TaskExecutor）
use_concurrency: true
max_concurrent_sessions: 32    # TaskExecutor的worker数量，建议值：CPU核心数 × 1.5-2
instances_per_pair: 16         # 每个pair预创建的实例数量（用于大规模优化）
use_instance_pool: true       # 是否启用实例池（总session > 100时自动启用）

# 内存优化参数（防止大规模模拟内存爆炸）
batch_write_size: 200         # 每N个session汇总后批量写入文件
max_buffer_size: 200         # 缓冲区最大大小，防止内存爆炸

# 硬件建议配置注释（根据你的机器选择）
# 4核CPU:  max_concurrent_sessions: 6-8
# 8核CPU:  max_concurrent_sessions: 12-16  
# 16核CPU: max_concurrent_sessions: 24-32
# 32核CPU: max_concurrent_sessions: 48-64

# 大规模模拟配置示例（注释状态）
# large_scale_config:
#   sessions_per_pair: 476190     # 对于1e7次总模拟：1e7/(玩家数×机器数)
#   max_concurrent_sessions: 16   # 根据CPU核心数调整
#   instances_per_pair: 2         # 减少内存使用
#   max_sim_duration: 7200        # 增加到2小时
#   output:
#     session_recording:
#       record_spins: false       # 大规模时关闭详细记录以节省空间

# 输出配置
output:
  # 目录设置
  directories:
    base_dir: "results"                       # 基础输出目录
    use_simulation_subdir: true               # 是否为每次模拟创建子目录
    simulation_dir_format: "sim_{timestamp}"  # 模拟目录名格式
    timestamp_format: "%Y%m%d-%H%M%S"         # 时间戳格式
    # simulation_name: "test"
  
  # 会话数据记录
  session_recording:
    enabled: true
    record_spins: true      # 小规模测试时保持true，大规模时改为false
    file_format: "csv"      # CSV格式更紧凑高效
  
  reports:
    generate_reports: true
    include:
      summary_report: true
      detailed_session_report: false

  # 界面反馈
  show_progress: true                  # 是否在控制台显示进度
  
  # 运行结束后自动清理
  auto_cleanup: false                  # 是否自动清理临时文件

# RNG configuration
rng:
  strategy: "mersenne"  # Options: mersenne, numpy
  seed: null  # Set to null for random seed or integer for fixed seed

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  console: true
  console_level: "INFO"
  file:
    enabled: true
    path: "logs/simulator.log"
    level: "DEBUG"
    max_bytes: 10485760  # 10 MB
    backup_count: 5
  loggers:
    domain: 
      level: INFO"  # 或 "ERROR"，只显示警告或错误
      propagate: true
    application:
      level: "INFO"
      propagate: true
    infrastructure:
      level: "INFO"
      propagate: true

# Analysis configuration
analysis:
  generate_reports: true
  output_dir: "reports"
  report_formats:
    - "json"
    - "html"
  metrics:
    - "rtp"
    - "volatility"
    - "hit_frequency"
    - "player_preferences"
    - "machine_popularity"
  include:
    summary_report: true             # 总体摘要
    player_preference_report: true   # 玩家偏好
    machine_performance_report: true # 机器性能
    detailed_session_report: false   # 详细会话报告（较大）

# 性能调优建议（注释形式）
# performance_tuning_notes: |
#   1. max_concurrent_sessions 调优：
#      - 从 CPU核心数 开始测试
#      - 如果CPU利用率不满，可以增加到 核心数×1.5-2
#      - 如果出现内存不足，需要减少并发数
#   
#   2. instances_per_pair 调优：
#      - 值太小：线程间竞争激烈，性能下降
#      - 值太大：内存占用过多
#      - 建议：2-5之间，根据内存情况调整
#   
#   3. 大规模模拟优化：
#      - 关闭 record_spins 以节省磁盘空间
#      - 增加 max_sim_duration 避免超时
#      - 考虑分批运行，避免单次运行时间过长