# src/application/config/simulation/default_simulation.yaml
# Simulation configuration

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  console: true
  console_level: "WARNING"
  file:
    enabled: true
    path: "logs/simulator.log"
    level: "DEBUG"
    max_bytes: 10485760  # 10 MB
    backup_count: 10
  loggers:
    domain: 
      level: "DEBUG"  # 或 "ERROR"，只显示警告或错误
      propagate: true
    application:
      level: "INFO"
      propagate: true
    infrastructure:
      level: "INFO"
      propagate: true

# 文件配置
file_configs:
  machines:
    dir: "src/application/config/machines"
    selection:
      include: ["newBee"]  # 包含模式：文件名包含这些字符串的会被选中
      exclude: ["default_", "fireworkShow", "risky"]  # 排除模式
  players:
    dir: "src/application/config/players"
    selection:
      include: ["v1_player_cluster0"]  # 包含模式：文件名包含这些字符串的会被选中
      exclude: []  # 排除模式

# Simulation parameters
max_spins: 15000          # 每个会话最大旋转次数
max_sim_duration: 1800    # 模拟器运行最大时长(秒)
max_player_duration: 86400 # 玩家逻辑时间最大值(秒)
initial_balance: 5000.0
sessions_per_pair: 1     # 当前测试值

# 并发控制参数
use_concurrency: true
max_concurrent_sessions: 16    # 实例池大小，建议值：CPU核心数 × 1.5-2

# 内存优化参数
batch_write_size: 50         # 每N个session汇总后批量写入文件
max_buffer_size: 200         # 缓冲区最大大小，防止内存爆炸

# RNG配置
rng:
  strategy: "mersenne"  # mersenne, system, numpy
  seed: null           # null表示使用随机种子，或指定具体数值
  per_worker: true     # 每个worker使用独立的RNG实例

# 输出配置
output:
  # 目录设置
  directories:
    base_dir: "results"
    use_simulation_subdir: true
    simulation_dir_format: "sim_{timestamp}"
    timestamp_format: "%Y%m%d_%H%M%S"

  # S3配置
  s3:
    use_s3: true
    bucket: "bituslabs-team-ai"
    region: "us-west-2"
    prefix: "gail_simulator_data_raw"
  
  # 会话数据记录
  session_recording:
    enabled: true
    record_spins: true
    file_format: "csv"
  
  # JSON格式化
  json_formatting:
    indent: 2
    compact_arrays: true
    ensure_ascii: false
  
  # 报告生成
  reports:
    generate_reports: true
    include:
      summary_report: true
      player_preference_report: true
      machine_performance_report: true
      detailed_session_report: false
  
  # 界面反馈
  show_progress: true
  auto_cleanup: false

# 分析配置
analysis:
  generate_reports: true
  output_dir: "reports"
  report_formats: ["json"]
  include:
    summary_report: true
    player_preference_report: true
    machine_performance_report: true
    detailed_session_report: false