# src/application/config/players/v1_player_cluster1.yaml
# V1模型玩家 - 聚类1

# 基本信息
player_id: "v1_cluster1_player"
name: "V1 Cluster 1 Player"
description: "V1模型训练的聚类0玩家"

# 玩家基本属性
currency: "CNY"

# 初始余额配置
initial_balance:
  avg: 144.57           # 余额平均值（必须）
  std: 1462.0780045410902           # 余额标准差
  min: 25.0            # 最小余额
  max: 3799.765           # 最大余额


# 模型版本
model_version: "v1"

# V1模型特定配置
model_config_v1:
  cluster_id: 1
  # 模型文件路径（相对于v1/model_files/目录）
  # base_model_dir: "path/to/custom/model/dir"  # 可选，如果不指定则使用默认路径
  
  # 基本约束
  min_delay: 2.0
  max_delay: 3.0
  default_delay: 1.0
  
  # 会话控制
  max_session_duration: 86400  # 最大会话时长（秒）
  max_spins_per_session: 15000  # 最大旋转次数

  first_bet_mapping:
    0.5: 20708825 
    1.0: 25957746
    2.5: 20226488
    5.0: 10036368
    8.0: 2486058
    15.0: 1361634
    20.0: 0
    25.0: 507730
    50.0: 110874
    70.0: 16014
    100.0: 21174
    250.0: 6190
    500.0: 2666
    1000.0: 1031
    2000.0: 817
    5000.0: 18