# src/application/config/players/v1_player_cluster0.yaml
# V1模型玩家 - 聚类0

# 基本信息
player_id: "v1_cluster0_player"
name: "V1 Cluster 0 Player"
description: "V1模型训练的聚类0玩家"

# 玩家基本属性
currency: "CNY"

# 初始余额配置
initial_balance:
  avg: 272.3          # 余额平均值（必须）
  std: 3218.162116598929          # 余额标准差
  min: 50.0                  # 最小余额
  max: 8317.7052915          # 最大余额 = +2.5std

# 模型版本
model_version: "v1"

# V1模型特定配置
model_config_v1:
  cluster_id: 0
  # 模型文件路径（相对于v1/model_files/目录）
  # base_model_dir: "path/to/custom/model/dir"  # 可选，如果不指定则使用默认路径
  
  # 基本约束
  min_delay: 2.0
  max_delay: 3.0
  default_delay: 1.0
  
  # 会话控制
  max_session_duration: 3600  # 最大会话时长（秒）
  max_spins_per_session: 500  # 最大旋转次数

  first_bet_mapping:
    0.5: 6617486
    1.0: 12389649
    2.5: 17502407
    5.0: 11196115
    8.0: 3892178
    15.0: 2314774
    25.0: 876125
    50.0: 200001
    70.0: 40075
    100.0: 36310
    250.0: 12000
    500.0: 6763
    1000.0: 2800
    2000.0: 1995
    5000.0: 191